### ISSUE TITLE
Provide the file name in getProxyUrl instead of using a FileNameGenerator

### ISSUE THREAD

**Issue by Guichaguri** [danikula/AndroidVideoCache#101]
It would be useful if there was an optional parameter in `getProxyUrl` for the filename, mainly when using random generated URLs

With the additional parameter:
```java
// streamUrl is a random generated URL provided by an API
// trackId is a fixed name that should be used as a filename
server.getProxyUrl(streamUrl, true, trackId);
```

Without the additional parameter:
```java
Map<String, String> trackUrls = new HashMap<>();

public void load(String streamUrl, String trackId) {
    trackUrls.put(streamUrl, trackId);
    server.getProxyUrl(streamUrl);
    // ...
}

@Override
public String generate(String url) {
    return trackUrls.get(url);
}
```
And you would still have to figure out when to remove the URL from the map, because `generate` is called multiple times

**Comment by danikula** [comment]
@Guichaguri use `FileNameGenerator` provided to `HttpProxyCacheServer .Builder`

**Comment by danikula** [comment]
See [sample code](https://github.com/danikula/AndroidVideoCache#providing-names-for-cached-files) in `README`
