### ISSUE TITLE
Cant catch Error or Exception in my APP

### ISSUE THREAD

**Issue by w420984** [danikula/AndroidVideoCache#107]
HI,
I want to catch Error or Exception in my APP, can you change method onError(Throwable e) in HttpProxyCacheServer.java to protect or public?

**Comment by danikula** [comment]
`HttpProxyCacheServer.onError` doesn't handle **all** library errors, so there is no sense to increase it visibility. Why do you need to handle errors?

**Comment by w420984** [comment]
@danikula if url is wrong or network is bad, my UI will always show loading
