### ISSUE TITLE
Does AndroidVideoCache support partial download / resume?

### ISSUE THREAD

**Issue by jpage4500** [danikula/AndroidVideoCache#111]
@danikula - sorry I could probably try looking at the code to figure this out but I was just wondering what happens today if a user starts streaming a video but doesn't finish watching it.

1) I assume the MediaPlayer (which I'm using to stream video) will stop trying to fetch the rest of the stream.. is that correct?

2) after MediaPlayer stops fetching data, does AndroidVideoCache continue to download the video in the background? (again I assume no but just want to double-check)

3) If a partially downloaded URL is requested again, will AndroidVideoCache return the partially downloaded file first before fetching the rest from the original source (URL)?

I'm not sure how #3 would work but it seems like it'd be a really big feature if it was possible.. saving clients from having to re-download partially complete streams

**Comment by danikula** [comment]
1. Correct
2. After MediaPlayer release data stream `AndroidVideoCache` stops downloading data. Partially downloaded file is stored in cache with postfix `.download`.
3. If same url is requested by MediaPlayer again `AndroidVideoCache` uses this partially downloaded cache, makes range request to server (with offset) and downloads rest of file.  Also  `AndroidVideoCache` uses partially downloaded cache in offline.

**Comment by mannol** [comment]
I'm experiencing problems with this feature. On the server side, I receive Range header containing the offset which equals the total size of the file. The server then returns 200 OK response with Content-Lenght: 0 because that's what's requested. This goes forever for some reason...
