### ISSUE TITLE
How to set cache directory

### ISSUE THREAD

**Issue by NightXlt** [danikula/AndroidVideoCache#118]
I've seen your sameple,but you use videoFragment's method(build(String url, String cachePath)) to set cache diretory,could I directly use method you defined instead of copying videoFragment to my module.I would appreciate you if you could tell me this method!

**Comment by danikula** [comment]
@NightXlt sure, you needn't any cache path. Cache root is set in `HttpProxyCacheServer`. I've [simplified `sample` app](https://github.com/danikula/AndroidVideoCache/commit/50b3a05e35372ec282c78d40fcbe8308bd5c330c).
