### ISSUE TITLE
Error processing request

### ISSUE THREAD

**Issue by 353338110** [danikula/AndroidVideoCache#119]
**when i use proxy.getProxyUrl(videoURL) ,it work good 
but when i use proxy.getProxyUrl(videoURL+"?avvod/m3u8/s/480x320/vb/480k") it cannot work**
[
![image](https://cloud.githubusercontent.com/assets/20110594/23536501/509cfade-0000-11e7-803e-d5d8b9fa1a10.png)
](url)

**Comment by danikula** [comment]
@353338110 Please, provide, full stacktrace and video url you use.

**Comment by danikula** [comment]
There is no needed information about this issue. We can reopen issue if @353338110  will provide it.
