### ISSUE TITLE
Supporting video bigger than 2GB

### ISSUE THREAD

**Issue by chyj4747** [danikula/AndroidVideoCache#122]
When I use this lib to cache video where size is bigger than 2GB, it can only cache 2GB data and then all threads(includes main ui thread) are stopped. So I changed 'int' to 'long' of this lib, it seems to work well(the file cached seems ok), but still, all threads are stopped.

**Comment by danikula** [comment]
@chyj4747 You are right. `AndroidVideoCache` uses type **int** in `Source` and `Cache` interfaces instead of **long**. So videos bigger than 2^31 will fail :( . We really must use `long` type.
