### ISSUE TITLE
Cannot resolve symbol 'VideoFragment_'

### ISSUE THREAD

**Issue by snehalpoyrekar** [danikula/AndroidVideoCache#124]

**Comment by danikula** [comment]
`sample` app uses `AndroidAnnotation` library and code generation at compile time. This class (`VideoFragment_`) is generated during assembling apk file. If you use gradle for building this file will be generated.

**Comment by chnouman** [comment]
i have tried but gradle is not building this file any other solution dear?

**Comment by chnouman** [comment]
i have figured it out.
