### ISSUE TITLE
HttpProxyCacheServer error

### ISSUE THREAD

**Issue by lygttpod** [danikula/AndroidVideoCache#126]
HttpProxyCacheServer error
           com.danikula.videocache.ProxyCacheException: Error processing request

Caused by: com.danikula.videocache.ProxyCacheException: Error opening connection for"myurl"

 Caused by: java.io.FileNotFoundException:"myurl"

how to fix this error

**Comment by lygttpod** [comment]
<img width="1160" alt="bug" src="https://cloud.githubusercontent.com/assets/11826777/24554051/d2a44b94-165e-11e7-8b2d-78479bc747ba.png">

**Comment by danikula** [comment]
@lygttpod Are you sure you have internet connection and internet permissions?
