### ISSUE TITLE
Error pinging server

### ISSUE THREAD

**Issue by Fajarrianda** [danikula/AndroidVideoCache#127]
i got this error.

Error reading ping response
com.danikula.videocache.ProxyCacheException: Error opening connection for http://127.0.0.1:33422/ping with offset 0
 Caused by: java.io.FileNotFoundException: http://127.0.0.1:33422/ping

**Comment by alfdev** [comment]
Hi @Fajarrianda,

i've the same issue, have you fixed it?

thank you

**Comment by danikula** [comment]
Duplicates #134
