### ISSUE TITLE
Use plugin on ant based project

### ISSUE THREAD

**Issue by ataafarin** [danikula/AndroidVideoCache#129]
hi,
is there any jar file of your plugin that i can use in my ant based project?

**Comment by danikula** [comment]
You can find any artifact for any version on [bintray](https://bintray.com/alexeydanilov/maven/videocache) page (for example [`aar`](https://bintray.com/alexeydanilov/maven/download_file?file_path=com%2Fdanikula%2Fvideocache%2F2.6.4%2Fvideocache-2.6.4.aar) for the version [2.6.4](https://bintray.com/alexeydanilov/maven/videocache/2.6.4))
