### ISSUE TITLE
how can breakpoint resume?

### ISSUE THREAD

**Issue by rong5690001** [danikula/AndroidVideoCache#130]

**Comment by danikula** [comment]
@rong5690001 What do you mean?

**Comment by rong5690001** [comment]
how can i pause the cache?

**Comment by rong5690001** [comment]
i have a business when is switching from wifi to mobile network,i need pause the cache.After user agree use mobile network, i need continue to cache.

**Comment by danikula** [comment]
If your app doesn't have any live player which streams video then AVD won't download video. But if you want to pause downloading cache **during** streaming by your player it is impossible.
