### ISSUE TITLE
Can't work in Farsi。

### ISSUE THREAD

**Issue by flztsj** [danikula/AndroidVideoCache#132]
We test it fail when user choose the system language to Farsi.

Need modify the code and add Locale.US for String.format function :

    private String newResponseHeaders(GetRequest request) throws IOException, ProxyCacheException {
        String mime = source.getMime();
        boolean mimeKnown = !TextUtils.isEmpty(mime);
        int length = cache.isCompleted() ? cache.available() : source.length();
        boolean lengthKnown = length >= 0;
        long contentLength = request.partial ? length - request.rangeOffset : length;
        boolean addRange = lengthKnown && request.partial;
        return new StringBuilder()
                .append(request.partial ? "HTTP/1.1 206 PARTIAL CONTENT\n" : "HTTP/1.1 200 OK\n")
                .append("Accept-Ranges: bytes\n")
                .append(lengthKnown ? String.format(Locale.US, "Content-Length: %d\n", contentLength) : "")
                .append(addRange ? String.format(Locale.US, "Content-Range: bytes %d-%d/%d\n", request.rangeOffset, length - 1, length) : "")
                .append(mimeKnown ? String.format(Locale.US, "Content-Type: %s\n", mime) : "")
                .append("\n") // headers end
                .toString();
    }

**Comment by danikula** [comment]
@flztsj can you make PR with fix & tests?

**Comment by danikula** [comment]
I tested it on Farsi and didn't notice any problem. Can you provide video url you have problem with?

**Comment by flztsj** [comment]
Do you clean the video cache before the test?

**Comment by danikula** [comment]
Yes, of course.

**Comment by danikula** [comment]
I've already fixed [similar](https://github.com/danikula/AndroidVideoCache/issues/87) issue.

**Comment by flztsj** [comment]
I konwn it ,so you need add this param for this function

**Comment by flztsj** [comment]
![default](https://cloud.githubusercontent.com/assets/5946178/25125421/5bbee2e4-2461-11e7-9c4b-526828a2e718.JPG)

**Comment by flztsj** [comment]
you can check the value of responseHeaders

**Comment by danikula** [comment]
I got. It is strange that I can't reproduce it. Anyway it should be changed as you mentioned above.
