### ISSUE TITLE
How to cache without player and retrieve all cached files.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [danikula/AndroidVideoCache#144]
1. How can i cache video or audio file without playing or passing proxy to player ?
2. How can i retrieve all cached audio or video files ?

**Comment by danikula** [comment]
1. it [has not been implemented yet](https://github.com/danikula/AndroidVideoCache/issues/23). You can use [this workaround](https://github.com/danikula/AndroidVideoCache/issues/59#issuecomment-267564871).
2.  Just fetch all files from disc cache folder. You can set cache folder in `HttpProxyCacheServer.Builder`
