### ISSUE TITLE
HttpUrlSource close

### ISSUE THREAD

**Issue by dadakkk** [danikula/AndroidVideoCache#146]
why the inputStream don't close when call the close method in HttpUrlSource class ?

**Comment by danikula** [comment]
@dadakkk See [docs](https://developer.android.com/reference/java/net/HttpURLConnection.html) for HttpURLConnection:
``` java
   URL url = new URL("http://www.android.com/");
   HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
   try {
     InputStream in = new BufferedInputStream(urlConnection.getInputStream());
     readStream(in);
   } finally {
     urlConnection.disconnect();
   }
```

>5. Disconnect. Once the response body has been read, the HttpURLConnection should be closed by calling disconnect(). Disconnecting releases the resources held by a connection so they may be closed or reused.
