### ISSUE TITLE
Cannot use JDK8 to compile the sample with library module

### ISSUE THREAD

**Issue by RoyaAoki** [danikula/AndroidVideoCache#15]
I need changed some files in the library module, so i modified sample/build.gradle to compile the library module
````
dependencies {
    compile project(':library')
    //compile 'com.danikula:videocache:2.1.1'
    ...
}
````

And i got this exception and build failed
````
Execution failed for task ':sample:preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
````

So i changed jdk version from 8 to 7 .then it build succeed.
But i also using retrolambda it need jdk8 to compile

So..how can i compile it use jdk8?

(sorry for my poor english)

**Comment by danikula** [comment]
I think your question is out of the scope library's code.

**Comment by RoyaAoki** [comment]
I find same case and solution
https://stackoverflow.com/questions/24662801/bad-class-file-magic-or-version

Just declare java version in the library's build.gradle:
````
sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7
````

**Comment by danikula** [comment]
@RoyaAoki thanks for sharing your solution.
