### ISSUE TITLE
Constantly seeing: A connection to http://127.0.0.1:54688/ was leaked

### ISSUE THREAD

**Issue by saket** [danikula/AndroidVideoCache#175]
Hello, I regularly see these warning logs from `OkHttpClient`:

`A connection to http://127.0.0.1:54688/ was leaked. Did you forget to close a response body?`

Is this a known issue or am I doing something wrong?

**Comment by harry248** [comment]
Same here...

**Comment by m7mdra** [comment]
same.

**Comment by Hackforid** [comment]
same to me,
when use ExoPlayer

**Comment by scar1et** [comment]
same to me, when use AndroidSystemPlayer
