### ISSUE TITLE
percentsAvailable are sometimes negative values

### ISSUE THREAD

**Issue by eshkoliGilad** [danikula/AndroidVideoCache#18]
percentsAvailable  in onCacheAvailable sometimes return negative values (-33, -32 and count up).

It happens when starting to stream/caching video, exit app and when return it shows those negative values.

Missing something here ?

**Comment by danikula** [comment]
[fixed](https://github.com/danikula/AndroidVideoCache/commit/6125478d27f4a3360903d529958a25609238277c) 
@eshkoliGilad thanks for reporting
