### ISSUE TITLE
为啥缓存的时候下载的.download文件非常大

### ISSUE THREAD

**Issue by aiven163** [danikula/AndroidVideoCache#184]
为啥缓存的时候下载的.download文件非常大，然后用播放器打开，发现是无线循环的在播放同一个源文件，源文件本来只有几兆，结果缓存文件几十兆，是什么原因，怎么修复。猜想是缓存的时候没有找到结束的未通知。不知道如何规避

**Comment by zhangshaobo87** [comment]
哥们 项目貌似是国外大神 写的吧  你说中文 他看不懂吧

**Comment by aiven163** [comment]
谢谢，我发现了。后来改为了英文

**Comment by Labmem003** [comment]
具体什么场景

**Comment by aiven163** [comment]
找到原因了，是因为服务器给地址的时候，下载文件没有给文件的content-length

**Comment by Hackforid** [comment]
Close your issue after fix it OK? @aiven163
