### ISSUE TITLE
cannot play video, because url append 127.0.0.1。

### ISSUE THREAD

**Issue by 1242128273wangpeng** [danikula/AndroidVideoCache#205]
why url append this？:
String.format(Locale.US, "http://%s:%d/%s", PROXY_HOST, port, ProxyCacheUtils.encode(url));
![qq20180412-220224](https://user-images.githubusercontent.com/10842360/38682339-6a4a8e2e-3e9d-11e8-865f-7d0341d4dd3f.png)

cause cannot play my video 。

**Comment by MichealWangDan** [comment]
How to fix that ?
