### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by anubhavmalik** [danikula/AndroidVideoCache#242]
@danikula  

Here are the queries I have regarding the library :-

1). Does the library auto-manage deleting the files if I set maximum file limit. If it does, what criteria is taken in consideration?

2). Does it load partial data for the first time automatically (similar to what a videoview would do).

3). When I set maxFileSize and the video size is greater than that, does the rest get directly streamed from the URL then?

You would help me save a lot of time by answering these questions.

Thanks in advance for your help.

**Comment by taoliuh** [comment]
Q1: It will auto delete cached files if the files count size exceeds the limit or the cached files total size exceeds the limit.
Q2: If the partial data is readable, it will load from the file cache every time.
Q3: The library does not support limiting the single cache file size. But I've tried to implemented this feature(NOT WORKING), if you want to limit all the SINGLE cached file size for 5M, while the video size is much more than 5M, maybe the player will not stream the reset of video(ijkplayer will throw an exception "end of stream -1000").

**Comment by anubhavmalik** [comment]
Thanks for the info ! :)
