### ISSUE TITLE
Pinging server error when set up System Http Proxy. 

### ISSUE THREAD

**Issue by ongakuer** [danikula/AndroidVideoCache#28]
Pinging server error when set up System Http Proxy. 

``` java
Error pinging server [attempt: 0, timeout: 200]. 
at java.util.concurrent.TimeoutException
at com.danikula.videocache.HttpProxyCacheServer.makeSureServerWorks
```

And It will work when add "127.0.0.1" to bypass list.

![http-proxy](https://cloud.githubusercontent.com/assets/1284428/10844600/aeccc392-7f3b-11e5-844b-72e49af74529.png)

**Comment by danikula** [comment]
So exotic bug. I love it )

**Comment by danikula** [comment]
@ongakuer Which version do you use ?

**Comment by ongakuer** [comment]
v2.3.3 , Nexus 4, Android 5.1.1

**Comment by molikto** [comment]
same here

**Comment by molikto** [comment]
http://stackoverflow.com/questions/32121792/bypass-proxy-to-access-localhost-in-android-programmatically so @danikula does this means this bug cannot be fixed?

**Comment by danikula** [comment]
[PR](https://github.com/danikula/AndroidVideoCache/pull/69). But I doubt it resolves problem.

**Comment by staylifer** [comment]
Does this problem be resolved? I meet the same bug, too.

**Comment by rong5690001** [comment]
me too
