### ISSUE TITLE
android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by FstTeam** [danikula/AndroidVideoCache#3]
i run example, and see white background on device. And i debug, i see  this exception : Method threw 'android.os.NetworkOnMainThreadException' exception. Pls help me. Tks

**Comment by danikula** [comment]
@FstTeam , please provide full stacktrace of the crash. What device and android version crash happen on?

**Comment by FstTeam** [comment]
@danikula now, i fixed my issue. tks. good luck.

**Comment by danikula** [comment]
@FstTeam can you describe problem? Was problem in my sample?

**Comment by FstTeam** [comment]
ak, maybe my network. i change other wifi and i see it run ok.
