### ISSUE TITLE
Failed to resolve: com.danikula:videocache:2.7.0. WHAT TO DO? Dependency not working!

### ISSUE THREAD

**Issue by vansh106** [danikula/AndroidVideoCache#311]

**Comment by vansh106** [comment]
add jcentre() in both build.gradle and settings.gradle()...

**Comment by rohit-mypcot** [comment]
still not working
build.gradle(app)
implementation 'com.danikula:videocache:2.7.1'

build.gradle(package):
repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://adcolony.bintray.com/AdColony" }
        maven { url 'https://maven.google.com' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/" }
        maven { url 'https://jitpack.io' }
        maven { url 'https://jcenter.bintray.com/' }
        jcenter() // Warning: this repository is going to shut down soon
    }

settings.gradle
repositories {
//        google()
//        mavenCentral()
//        maven { url "https://jitpack.io" }
//        maven { url 'https://maven.google.com' }
//        jcenter() // Warning: this repository is going to shut down soon
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://adcolony.bintray.com/AdColony" }
        maven { url 'https://maven.google.com' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/" }
        maven { url 'https://jitpack.io' }
        maven { url 'https://jcenter.bintray.com/' }
        jcenter()
    }

Failed to resolve: com.danikula:videocache:2.7.1
Show in Project Structure dialog
Show Details
Affected Modules: app

**Comment by vansh106** [comment]
Lol you aliveOn 20 Sep 2024, at 3:52 PM, rohit-mypcot ***@***.***> wrote:﻿
still not working
build.gradle(app)
implementation 'com.danikula:videocache:2.7.1'
build.gradle(package):
repositories {
google()
mavenCentral()
gradlePluginPortal()
maven { url "https://adcolony.bintray.com/AdColony" }
maven { url 'https://maven.google.com' }
maven { url 'https://plugins.gradle.org/m2/' }
maven { url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/" }
maven { url 'https://jitpack.io' }
maven { url 'https://jcenter.bintray.com/' }
jcenter() // Warning: this repository is going to shut down soon
}
settings.gradle
repositories {
//        google()
//        mavenCentral()
//        maven { url "https://jitpack.io" }
//        maven { url 'https://maven.google.com' }
//        jcenter() // Warning: this repository is going to shut down soon
google()
mavenCentral()
gradlePluginPortal()
maven { url "https://adcolony.bintray.com/AdColony" }
maven { url 'https://maven.google.com' }
maven { url 'https://plugins.gradle.org/m2/' }
maven { url "https://s3-ap-southeast-1.amazonaws.com/godel-release/godel/" }
maven { url 'https://jitpack.io' }
maven { url 'https://jcenter.bintray.com/' }
jcenter()
}
Failed to resolve: com.danikula:videocache:2.7.1
Show in Project Structure dialog
Show Details
Affected Modules: app

**Comment by rohit-mypcot** [comment]
is there a way out to this issue or is the repo dead?

**Comment by vansh106** [comment]
Worked at this in 2021, no clue.Sent from my iPhoneOn 20 Sep 2024, at 4:35 PM, rohit-mypcot ***@***.***> wrote:﻿
is there a way out to this issue or is the repo dead?

**Comment by vansh106** [comment]
But 99% sure its dead, no replies whatsoever I got. Sent from my iPhoneOn 20 Sep 2024, at 4:35 PM, rohit-mypcot ***@***.***> wrote:﻿
is there a way out to this issue or is the repo dead?

**Comment by wojtow** [comment]
> is there a way out to this issue or is the repo dead?

I'd suspect the repo is dead.  With Media3 Exoplayer built into Android having various cache options  that are more configurable and which seem to work pretty well, there's not really much need of this anymore I wouldn't think.

**Comment by ouyangzhixuan** [comment]
> is there a way out to this issue or is the repo dead?

add  maven { url "https://repository.axelor.com/nexus/repository/maven-public" } into your build.gradle

**Comment by vansh106** [comment]
Look for alternatives.Sent from my iPhoneOn 27 Nov 2024, at 10:00 AM, Youmu ***@***.***> wrote:﻿

is there a way out to this issue or is the repo dead?

add  maven { url "https://repository.axelor.com/nexus/repository/maven-public" } into your build.gradle
