### ISSUE TITLE
Cache not working when used from a view

### ISSUE THREAD

**Issue by ketanbhatt** [danikula/AndroidVideoCache#34]
I am using the factory method to maintain one instance of the proxy. And feeding proxy-url to the data source for the media player.

```
HttpProxyCacheServer proxy = HttpProxyCacheServerFactory.getProxy(getContext());
String proxyUrl = proxy.getProxyUrl(mediaUrl);
this.mediaUrl = proxyUrl;
```

This logic is in my mediaplayer view, which means a new proxy-url gets created every time the view is created. 
1. Does the proxy server create a new proxy-url for the same url every time I call `getProxyUrl()` ?
2. Where is the logic that if the file is previously loaded, then the proxy-url points to this file.
3. What happens if the file was only partially loaded and I seek back, would the file stream again, or it will load from the already loaded cache?

Right now my cache doesn't seem to work as network calls are made every time I play the file.

**Comment by vikasgulati** [comment]
@ketanbhatt Oddly it (cache) seems to work for me when I turn off the internet connection. Does it work for you?

**Comment by danikula** [comment]
@ketanbhatt 
1. For same url proxy will return same proxied url
2. Library generates unique name of cache file for your url and uses this file in `FileCache`
3. Library will use downloaded part of video.

If you have any problem with library, please, create new issue and describe it as detail as you can (preconditions, device info, library version, stacktrace, etc.)
