### ISSUE TITLE
Cache isn't continue when pause mediaplayer.

### ISSUE THREAD

**Issue by danglephuc** [danikula/AndroidVideoCache#36]
I have using VideoCache for loading video from the url to my MediaPlayer. The cache is running to 30 - 35 percents and pause when i set datasourec. After this, i'm not playing the video, so the cache isn't continuing cache. How can I continue cache the file when the mediaplayer not play?

**Comment by danikula** [comment]
I think it related to [43](https://github.com/danikula/AndroidVideoCache/issues/43). Fix will be available in 2.5.0
