### ISSUE TITLE
Should use "HEAD" method for HttpUrlSource.fetchContentInfo() instead of "GET"

### ISSUE THREAD

**Issue by liyzay** [danikula/AndroidVideoCache#40]
For some devices,the HttpURLConnection.disconnect() method could cost too much time,see this:
http://stackoverflow.com/questions/25423546/httpurlconnection-slow-to-disconnect-java-android
The [HttpUrlSource.fetchContentInfo()](https://github.com/danikula/AndroidVideoCache/blob/master/library/src/main/java/com/danikula/videocache/HttpUrlSource.java) method only get the length and mime which is just in the http response`s header,not the body,so "HEAD" would be a better choice.

**Comment by danikula** [comment]
@liyzay Some servers [doesn't response to HEAD requests](https://github.com/danikula/AndroidVideoCache/issues/27). What is why I [removed](https://github.com/danikula/AndroidVideoCache/commit/a270460c8d9b4afde1c113029d6add751e7be07d) HEAD requests
