### ISSUE TITLE
Should cache the "length" and "mime" in HttpUrlSource

### ISSUE THREAD

**Issue by liyzay** [danikula/AndroidVideoCache#41]
Should cache the "length" and "mime" in [HttpUrlSource](https://github.com/danikula/AndroidVideoCache/blob/master/library/src/main/java/com/danikula/videocache/HttpUrlSource.java) so it wont open/close connection frequently ,which will cost less time and resource.

**Comment by danikula** [comment]
[Same issue](https://github.com/danikula/AndroidVideoCache/issues/45)
