### ISSUE TITLE
Typo in Library DEFAULT_MAX_SIZE

### ISSUE THREAD

**Issue by Puliyo** [danikula/AndroidVideoCache#44]
Hi,

From library, it seems the DEFAULT_MAX_SIZE is 51.2MB

https://github.com/danikula/AndroidVideoCache/blob/master/library/src/main/java/com/danikula/videocache/HttpProxyCacheServer.java#L348

**Comment by danikula** [comment]
[PR](https://github.com/danikula/AndroidVideoCache/pull/58)

**Comment by danikula** [comment]
Fixed in PR. @Puliyo thanks for issue.
