### ISSUE TITLE
HttpUrlSource.fetchContentInfo() cost too much time on some devices

### ISSUE THREAD

**Issue by liyzay** [danikula/AndroidVideoCache#45]
After I changed [HttpUrlSource.fetchContentInfo()](https://github.com/danikula/AndroidVideoCache/blob/master/library/src/main/java/com/danikula/videocache/HttpUrlSource.java#L103) by using "HEAD" method,it still cost too much time to disconnect the HttpURLConnection.I have test my code with two android devices,sometimes fetchContentInfo() will finish quickly,sometimes it will cost 5 or 20 seconds.So I changed HttpUrlSource with [okhttp](https://github.com/square/okhttp) and it performs better.

**Comment by quangtrung89** [comment]
Hi @liyzay ,

How can u replace HttpUrlSource by okhttp? Can you share it here?

Thanks,
Trung.

**Comment by liyzay** [comment]
Hi @quangtrung89 ,here are the steps:
1. Creating a new class **UrlSource** implements [com.danikula.videocache.Source](https://github.com/danikula/AndroidVideoCache/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdanikula%2Fvideocache%2FSource.java);
2. Creating a new class **OkHttpSource** extends **UrlSource**;
3. Replacing the code where **HttpUrlSource** are used,here in [HttpProxyCache](https://github.com/danikula/AndroidVideoCache/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdanikula%2Fvideocache%2FHttpProxyCache.java#l87) and in [HttpProxyCacheServerClients](https://github.com/danikula/AndroidVideoCache/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fdanikula%2Fvideocache%2FHttpProxyCacheServerClients.java#L82)
Here are the codes:
**UrlSource**:
package com.danikula.videocache;

public abstract class UrlSource implements Source{
    protected String url;
    protected volatile int length = Integer.MIN_VALUE;
    protected volatile String mime;

    public UrlSource(String url){
        this.url = url ;
    }

    public UrlSource(UrlSource urlSource){
        this.url = urlSource.url;
        this.length = urlSource.length;
        this.mime = urlSource.mime ;
    }

    public abstract String getMime() throws ProxyCacheException;

    @Override
    public String toString() {
        return "UrlSource{" +
                "url='" + url + '\'' +
                ", length=" + length +
                ", mime='" + mime + '\'' +
                '}';
    }
}

**OkHttpSource**

package com.danikula.videocache;

import android.text.TextUtils;

import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InterruptedIOException;
import java.util.concurrent.TimeUnit;

import static com.danikula.videocache.ProxyCacheUtils.DEFAULT_BUFFER_SIZE;
import static com.danikula.videocache.ProxyCacheUtils.LOG_TAG;
import static java.net.HttpURLConnection.HTTP_OK;
import static java.net.HttpURLConnection.HTTP_PARTIAL;

public class OkHttpSource extends UrlSource{
    private static final int MAX_REDIRECTS = 5;
    //
    private IMimeCache mimeCache ;
    private OkHttpClient httpClient = new OkHttpClient();
    private InputStream inputStream;

    public OkHttpSource(IMimeCache mimeCache,String url) {
        super(url);
        this.mimeCache = mimeCache ;
    }

    public OkHttpSource(UrlSource urlSource){
        super(urlSource);
    }

    @Override
    public int length() throws ProxyCacheException {
        if (length == Integer.MIN_VALUE) {
            tryLoadMimeCache();
        }
        if (length == Integer.MIN_VALUE) {
            fetchContentInfo();
        }
        return length;
    }

    @Override
    public String getMime() throws ProxyCacheException {
        if (TextUtils.isEmpty(mime)) {
            tryLoadMimeCache();
        }
        if (TextUtils.isEmpty(mime)) {
            fetchContentInfo();
        }
        return mime;
    }

    @Override
    public void open(int offset) throws ProxyCacheException {
        try {
            Response response = openConnection(offset, -1);
            mime = response.body().contentType().toString();
            length = readSourceAvailableBytes(response, offset);
            inputStream = new BufferedInputStream(response.body().byteStream(), DEFAULT_BUFFER_SIZE);
        } catch (IOException e) {
            throw new ProxyCacheException("Error opening connection for " + url + " with offset " + offset, e);
        }
    }

    private int readSourceAvailableBytes(Response response, int offset) throws IOException {
        int responseCode = response.code() ;
        int contentLength = (int) response.body().contentLength();
        return responseCode == HTTP_OK ? contentLength
                : responseCode == HTTP_PARTIAL ? contentLength + offset : length;
    }

    @Override
    public int read(byte[] buffer) throws ProxyCacheException {
        if (inputStream == null) {
            throw new ProxyCacheException("Error reading data from " + url + ": connection is absent!");
        }
        try {
            return inputStream.read(buffer, 0, buffer.length);
        } catch (InterruptedIOException e) {
            throw new InterruptedProxyCacheException("Reading source " + url + " is interrupted", e);
        } catch (IOException e) {
            throw new ProxyCacheException("Error reading data from " + url, e);
        }
    }

    @Override
    public void close() throws ProxyCacheException {
        ProxyCacheUtils.close(inputStream);
    }

    private void fetchContentInfo() throws ProxyCacheException {
        VideoCacheLog.d(LOG_TAG, "Read content info from " + url);
        Response response = null ;
        try {
            response = openConnectionForHeader(10000);
            if(response==null || !response.isSuccessful()){
                throw new ProxyCacheException("Fail to fetchContentInfo: " + url);
            }
            length = (int) response.body().contentLength();
            mime = response.body().contentType().toString();
            tryPutMimeCache();
            VideoCacheLog.i(LOG_TAG, "Content info for `" + url + "`: mime: " + mime + ", content-length: " + length);
        } catch (IOException e) {
            VideoCacheLog.e(LOG_TAG, "Error fetching info from " + url, e);
        } finally {
            VideoCacheLog.d(LOG_TAG, "Closed connection from :" + url);
        }
    }

    private Response openConnectionForHeader(int timeout) throws IOException, ProxyCacheException {
        if(timeout>0){
            httpClient.setConnectTimeout(timeout, TimeUnit.MILLISECONDS);
            httpClient.setReadTimeout(timeout, TimeUnit.MILLISECONDS);
            httpClient.setWriteTimeout(timeout, TimeUnit.MILLISECONDS);
        }
        Response response ;
        boolean isRedirect = false;
        String newUrl = this.url ;
        int redirectCount = 0;
        do {
            Request request = new Request.Builder()
                    .head()
                    .url(newUrl)
                    .build();
            response = httpClient.newCall(request).execute();
            if(response.isRedirect()){
                newUrl = response.header("Location");
                isRedirect = response.isRedirect() ;
                redirectCount++;
            }
            if(redirectCount>MAX_REDIRECTS){
                throw new ProxyCacheException("Too many redirects: " + redirectCount);
            }
        }while (isRedirect);

        return response ;
    }

    private Response openConnection(int offset,int timeout) throws IOException, ProxyCacheException {
        if(timeout>0){
            httpClient.setConnectTimeout(timeout, TimeUnit.MILLISECONDS);
            httpClient.setReadTimeout(timeout, TimeUnit.MILLISECONDS);
            httpClient.setWriteTimeout(timeout, TimeUnit.MILLISECONDS);
        }
        Response response ;
        boolean isRedirect = false;
        String newUrl = this.url ;
        int redirectCount = 0;
        do {
            VideoCacheLog.d(LOG_TAG, "Open connection" + (offset > 0 ? " with offset " + offset : "") + " to " + url);
            Request.Builder requestBuilder = new Request.Builder();
            requestBuilder.get();
            requestBuilder.url(newUrl);
            if (offset > 0) {
                requestBuilder.addHeader("Range", "bytes=" + offset + "-");
            }
            response = httpClient.newCall(requestBuilder.build()).execute();
            if(response.isRedirect()){
                newUrl = response.header("Location");
                isRedirect = response.isRedirect() ;
                redirectCount++;
            }
            if(redirectCount>MAX_REDIRECTS){
                throw new ProxyCacheException("Too many redirects: " + redirectCount);
            }
        }while (isRedirect);

        return response ;
    }

    private void tryLoadMimeCache(){
        if(mimeCache!=null){
            UrlMime urlMime = mimeCache.getMime(url);
            if(urlMime!=null && !TextUtils.isEmpty(urlMime.getMime()) && urlMime.getLength()!=Integer.MIN_VALUE){
                this.mime = urlMime.getMime();
                this.length = urlMime.getLength() ;
            }
        }
    }

    private void tryPutMimeCache(){
        if(mimeCache!=null){
            mimeCache.putMime(url,length,mime);
        }
    }
}

**PS:** I use the **IMimeCache** for caching mime and length of url ,you can just remove it.

**Comment by quangtrung89** [comment]
Thanks a lot, I works nice and smooth (y).

**Comment by danikula** [comment]
Will fixed in 2.6.0 with help of content info cache.
