### ISSUE TITLE
Media Player recording data usage

### ISSUE THREAD

**Issue by brittonjg** [danikula/AndroidVideoCache#51]
I've noticed that the Android Media player is adding to the Data Usage used counter for our application when setting the player to use getProxyUrl()

I believe this is because the Android Media Player thinks it's playing from an internet source, even though it is streaming locally from the device. This is also happening within your sample application. Is there any way to stop this from happening as it looks like the application is using much data that it really is. This is also apparent in the Android Studio Network tool which is showing a network usage EVENT though I have no data connection and if I have airplane mode off. 

I am unsure whether this is more related to this library or it's completely down to Android. I've been testing this on Android 6 Nexus 5

**Comment by brittonjg** [comment]
Is the correct implementation, that if a user is connected to the internet then the file will be downloaded regardless as to whether it is in the cache or not? That is what I am currently seeing on my Nexus 6P, even when I use your sample application and Android Studios Network Statistics panel.

Unless the Network panel can't differentiate between external and local network communication. Which could very possibly be the case.

**Comment by brittonjg** [comment]
After some investigation adding connection.setRequestMethod("HEAD"); into HttpUrlSource.openConnection may help, but it doesn't fix the issue.

I am more convinced Android is reporting the data incorrectly.

**Comment by danikula** [comment]
@brittonjg You can check was the file fully cached by method `HttpProxyCacheServer.isCached(String url)`. If it was cached you can use local file uri directly to file instead of proxied url.
