### ISSUE TITLE
FileNotFoundException in opening source

### ISSUE THREAD

**Issue by cliguo** [danikula/AndroidVideoCache#52]
Video files are real,run the example error:
<img width="861" alt="error1" src="https://cloud.githubusercontent.com/assets/224387/12320572/5210887a-bae4-11e5-9935-e54b65525ba5.png">
<img width="866" alt="error2" src="https://cloud.githubusercontent.com/assets/224387/12320573/52246408-bae4-11e5-9e18-62f5eedc9abd.png">

**Comment by danikula** [comment]
@cliguo It seems your manifest doesn't contain internet permissions. That is why you can't open `HttpURLConnection`
