### ISSUE TITLE
Video is not caching

### ISSUE THREAD

**Issue by Disord** [danikula/AndroidVideoCache#56]
Hello! I have a next problem: video is not caching while streaming. I used a standart mediaplayer. There is the code:

        HttpProxyCacheServer proxy = ProxyFactory.getProxy(videoPlayerActivity);
        String proxyUrl = proxy.getProxyUrl(API.URL + API.videoView + videos.get(videoNum).getFileName());
        videoPlayer.setVideoPath(proxyUrl);

ProxyFactory - is a simple singletone.
So video streaming is ok, but caching won't work. Here is the log (same everytime):

```
I/ProxyCache: Proxy cache server started. Ping it...
D/ProxyCache: Open connection  to http://127.0.0.1:41106/ping
D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=37627,localPort=41106]
I/ProxyCache: Request to cache proxy:GetRequest{rangeOffset=0, partial=false, uri='ping'}
D/ProxyCache: Opened connections: 0
D/ProxyCache: Ping response: `ping ok`, pinged? true
D/MediaPlayer: Couldn't open file on client side, trying server side
D/ProxyCache: Accept new socket Socket[address=/127.0.0.1,port=37628,localPort=41106]
I/ProxyCache: Request to cache proxy:GetRequest{rangeOffset=0, partial=false, uri='http%3A%2F%2Fmarshall-video.dev.begemot-begemot.ru%2Fuploads%2Ftest1213.mp4'}
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@41acedc0 time:31379668
D/ProxyCache: Read content info from http://marshall-video.dev.begemot-begemot.ru/uploads/test1213.mp4
D/ProxyCache: Open connection  to http://marshall-video.dev.begemot-begemot.ru/uploads/test1213.mp4
I/ProxyCache: Content info for `http://marshall-video.dev.begemot-begemot.ru/uploads/test1213.mp4`: mime: video/mp4, content-length: 1206921
D/ProxyCache: Shutdown proxy for HttpUrlSource{url='http://marshall-video.dev.begemot-begemot.ru/uploads/test1213.mp4}
D/ProxyCache: Opened connections: 0
```

**Comment by brittonjg** [comment]
@Disord I believe I have the same issue that you have been having.

If you prevent your device from having an internet connection, but try and play the video again does it play?

**Comment by danikula** [comment]
@Disord Is this issue still actual for you? Do you use the latest and most stable version 2.5.0?

**Comment by Disord** [comment]
@danikula This issue is not actual for me, sorry. Project with that plug-in I was already finished, and I forgot how I solve this problem. I think, it was my mistake. I'm sorry, but now I have not access to sources of that project. Problem solved, thank you. And I think, it is not your mistake in your plug-in.

**Comment by tyrootechnology** [comment]
@Disord  I am facing the same problem in my project. Can you please help me resolve this issue ??

`D/HttpUrlSource: 2018-03-13 17:23:35.095 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                            Open connection  to http://127.0.0.1:34809/ping
D/HttpProxyCacheServer: 2018-03-13 17:23:35.102 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Accept new socket Socket[address=/127.0.0.1,port=35179,localPort=34809]
D/HttpProxyCacheServer: 2018-03-13 17:23:35.104 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Request to cache proxy:GetRequest{rangeOffset=0, partial=false, uri='ping'}
I/Pinger: 2018-03-13 17:23:35.107 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                     Ping response: `ping ok`, pinged? true
D/HttpUrlSource: 2018-03-13 17:23:35.108 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                            Open connection  to http://127.0.0.1:34809/ping
D/HttpProxyCacheServer: 2018-03-13 17:23:35.111 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Opened connections: 0
D/HttpProxyCacheServer: 2018-03-13 17:23:35.112 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Accept new socket Socket[address=/127.0.0.1,port=49057,localPort=34809]
D/HttpProxyCacheServer: 2018-03-13 17:23:35.118 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Request to cache proxy:GetRequest{rangeOffset=0, partial=false, uri='ping'}
I/Pinger: 2018-03-13 17:23:35.120 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                     Ping response: `ping ok`, pinged? true
D/HttpProxyCacheServer: 2018-03-13 17:23:35.122 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Opened connections: 0
D/HttpProxyCacheServer: 2018-03-13 17:23:35.125 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Accept new socket Socket[address=/127.0.0.1,port=33176,localPort=34809]
W/System.err: java.io.EOFException
W/System.err:     at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
W/System.err:     at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
D/HttpProxyCacheServer: 2018-03-13 17:23:35.129 org.slf4j.impl.AndroidLoggerAdapter.log(AndroidLoggerAdapter.java:55)
                                                                                   Opened connections: 0
W/System.err:     at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:398)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:342)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:209)
W/System.err:     at java.net.URL.openStream(URL.java:470)`
