### ISSUE TITLE
Can I cache video without using videoview? 

### ISSUE THREAD

**Issue by quangtrung89** [danikula/AndroidVideoCache#59]
Can I cache video without using videoview?

**Comment by jarrodholliday** [comment]
Yes you can. Way I'm currently doing it is by opening a stream from the url generated by the proxy and reading the data real quick. That'll kick start the cache to download the file.
`HttpProxyCacheServer proxy = VyngApplication.getProxy(VyngApplication.getInstance().getApplicationContext());
        proxy.registerCacheListener((cacheFile, url, percentsAvailable) ->
                Logger.v("%d%% available for url %s", percentsAvailable, url), videoUrl);
        InputStream is = null;
        try {
            URL url = new URL(proxy.getProxyUrl(videoUrl));
            is = url.openStream();
            byte[] byteChunk = IOUtils.toByteArray(is);
        } catch (Exception e) {
            Logger.d("Failed while reading bytes from %s: %s", videoUrl, e.getMessage());
        } finally {
            if(is != null) {
                try {
                    is.close();
                } catch (IOException e) {
                    // Long hair, don't care.
                }
            }
        }`

**Comment by jarrodholliday** [comment]
Yes you can, currently the way I'm doing it is opening a stream with the url and reading bytes from the stream to kick start the cache download.

`HttpProxyCacheServer proxy = VyngApplication.getProxy(VyngApplication.getInstance().getApplicationContext());

        proxy.registerCacheListener((cacheFile, url, percentsAvailable) ->
                Logger.v("%d%% available for url %s", percentsAvailable, url), videoUrl);

        InputStream is = null;

        try {
            URL url = new URL(proxy.getProxyUrl(videoUrl));
            is = url.openStream();
            byte[] byteChunk = IOUtils.toByteArray(is);
        } catch (Exception e) {
            Logger.d("Failed while reading bytes from %s: %s", videoUrl, e.getMessage());
        } finally {
            if(is != null) {
                try {
                    is.close();
                } catch (IOException e) {
                    // Long hair, don't care.
                }
            }
        }`

**Comment by quangtrung89** [comment]
Thanks Jarrod :).

**Comment by kaleemTorres** [comment]
Hi I am new to Android, can you explain a little bit more about your implementation

**Comment by jarrodholliday** [comment]
Hey @kaleemTorres , the library starts caching the video when a connection to the URL is opened and data transfers. So in order to pre-fetch and download videos to the cache without playing the video in a VideoView(or other video player) we get a cache url from the library and open a stream to the url. Then in this example using the Apache Commons-IO library(https://commons.apache.org/proper/commons-io/) we read all the bytes of the stream to a byte array and the cache saves it to disk auto-magically.

**Comment by kaleemTorres** [comment]
Thanks @jarrodholliday for easy to understand  explanation. It really solved my problem.

**Comment by danikula** [comment]
@jarrodholliday 's solutions works perfectly. I gonna add some prefetch functionality directly in library in future.

**Comment by danikula** [comment]
[Ability to pre-cache file asynchronously](https://github.com/danikula/AndroidVideoCache/issues/23)

**Comment by farbod-s** [comment]
@jarrodholliday @danikula
how can i pause and resume download process for cached file after opening stream to the remote url and reading bytes from the stream.
i'm using HttpProxyCacheServer for cache streaming multimedia files and now i want to let the user download the rest of file or vise versa (download a piece of file first and stream the rest of it). at the end, whenever a cached file is complete the user can play it normally.
i appreciate any kind of help.

**Comment by danikula** [comment]
@farbod-s You have no control under caching process. You can't pause or resume it manually. Caching starts as soon as you invoke request to `proxied` url and finishes as soon as you close connection to this url or `HttpProxyCacheServer` downloads whole file. Also you can pre-cache file without `MediaPlayer` as @jarrodholliday [suggest](https://github.com/danikula/AndroidVideoCache/issues/59#issuecomment-191576975)

**Comment by farbod-s** [comment]
@danikula is it possible to using `HttpProxyCacheServer` as a proxy for [OkHttpClient](https://github.com/square/okhttp/)?
i have a download manager and cache streaming media with `HttpProxyCacheServer`, now i want to use the download cache for streaming cache and vise versa.

**Comment by ltpquang** [comment]
Sorry for digging this up, but using `IOUtils.toByteArray()` throws me OutOfMem exceptions on big videos (since the whole video will be stored on memory), so I came up with the following:
```
URL url = new URL(httpProxyCacheServer.getProxyUrl(videoLink));
InputStream inputStream = url.openStream();
int bufferSize = 1024;
byte[] buffer = new byte[bufferSize];
int length = 0;
while ((length = inputStream.read(buffer)) != -1) {
//Since we just need to kick start the prefetching, dont need to do anything here
//  or we can use ByteArrayOutputStream to write down the data to disk
}
```

**Comment by jarrodholliday** [comment]
It's ok @ltpquang, always good to get updated info on things. I ended up doing the same thing as well, but because the Apache Commons library wasn't needed for anything else anymore so no sense having it for one use.

**Comment by danikula** [comment]
Sure you should save to byte array data from stream to avoid OOM. ltpquang's solution is the best way to precache files.

**Comment by pravynandas** [comment]
Thanks a ton @jarrodholliday and @ltpquang ... working great after merging both solutions. 

As a side note, it is advisable to reference the cache listener as a variable and Unregister once the download reaches 100% otherwise it may cause memory leak as suggested by the README.

```
@Override
public void onCacheAvailable(File cacheFile, String url, int percentsAvailable) {
	if (percentsAvailable == 100) {
		try {
			proxy.unregisterCacheListener(this);
		} catch (Exception e) {}
	}
	Log.d(LOG_TAG, String.format("%d%% available for url %s", percentsAvailable, url));
}
```

**Comment by paragwadhwani** [comment]
> Sorry for digging this up, but using `IOUtils.toByteArray()` throws me OutOfMem exceptions on big videos (since the whole video will be stored on memory), so I came up with the following:
> 
> ```
> URL url = new URL(httpProxyCacheServer.getProxyUrl(videoLink));
> InputStream inputStream = url.openStream();
> int bufferSize = 1024;
> byte[] buffer = new byte[bufferSize];
> int length = 0;
> while ((length = inputStream.read(buffer)) != -1) {
> //Since we just need to kick start the prefetching, dont need to do anything here
> //  or we can use ByteArrayOutputStream to write down the data to disk
> }
> ```

@danikula @jarrodholliday @ltpquang @pravynandas thanks for this solution for pre loading a file
I have tried this for my app its working fine but there is a problem when we re hitting our ProxyURL its downloading a file in cache folder for our video
but its continuously downloading that file even if my file size is 5MB(On server) its continuously downloading file which crosses 200MB(On local cache folder ) and after that also increasing file size and downloading ....
and even when I exit my App its downloading that files .
and when I turn my data connection off it stops that downloading process but if my data connection on it continuously use that data and increase that file size .
Please have a look.....

**Comment by qulj** [comment]
> Sorry for digging this up, but using `IOUtils.toByteArray()` throws me OutOfMem exceptions on big videos (since the whole video will be stored on memory), so I came up with the following:
> 
> ```
> URL url = new URL(httpProxyCacheServer.getProxyUrl(videoLink));
> InputStream inputStream = url.openStream();
> int bufferSize = 1024;
> byte[] buffer = new byte[bufferSize];
> int length = 0;
> while ((length = inputStream.read(buffer)) != -1) {
> //Since we just need to kick start the prefetching, dont need to do anything here
> //  or we can use ByteArrayOutputStream to write down the data to disk
> }
> ```

//Since we just need to kick start the prefetching, dont need to do anything here
你好，请教下，这个只请求流，而不写入磁盘，是能达到缓存的效果吗？

**Comment by ltpquang** [comment]
> > Sorry for digging this up, but using `IOUtils.toByteArray()` throws me OutOfMem exceptions on big videos (since the whole video will be stored on memory), so I came up with the following:
> > ```
> > URL url = new URL(httpProxyCacheServer.getProxyUrl(videoLink));
> > InputStream inputStream = url.openStream();
> > int bufferSize = 1024;
> > byte[] buffer = new byte[bufferSize];
> > int length = 0;
> > while ((length = inputStream.read(buffer)) != -1) {
> > //Since we just need to kick start the prefetching, dont need to do anything here
> > //  or we can use ByteArrayOutputStream to write down the data to disk
> > }
> > ```
> 
> //Since we just need to kick start the prefetching, dont need to do anything here 你好，请教下，这个只请求流，而不写入磁盘，是能达到缓存的效果吗？

Yes, it does. In fact, you are not requesting directly to the file but through a proxy url, the proxy server will know and kickstart the caching.
