### ISSUE TITLE
Proxy server isn't pinged

### ISSUE THREAD

**Issue by shawwinbin** [danikula/AndroidVideoCache#68]
I get the issue Proxy server isn't pinged

in samsung galaxy note 4  android 5.0.1

**Comment by shawwinbin** [comment]
Proxy server isn't pinged. Caching doesn't work. If you see this message, please, email me danikula@gmail.com

**Comment by gajicm93** [comment]
+1

**Comment by gajicm93** [comment]
For me it happens only on data connection, WiFi works fine..

**Comment by ThatOdieGuy** [comment]
I had a problem with this when my device had a proxy setup in the system settings. Check your network settings, you might have a proxy setup.

I made this commit/pull request to fix it.
https://github.com/danikula/AndroidVideoCache/pull/69

After you fix that, you may need to change your client code to also not use the system proxy.

**Comment by danikula** [comment]
Duplicates [28](https://github.com/danikula/AndroidVideoCache/issues/28)
