### ISSUE TITLE
How can set expiration policy for cache file?

### ISSUE THREAD

**Issue by IRMobydick** [danikula/AndroidVideoCache#7]
Hi there,
First of all, I should say thank you for sharing this library :smiley: 
In next, how can manage this cache file? for example delete by a Expiration date?

thanks you again

**Comment by danikula** [comment]
@IRMobydick Thanks.
In current implementation you have to manage lifecycle of cache. I plan to implement it in the next version.

**Comment by danikula** [comment]
[Related issue](https://github.com/danikula/AndroidVideoCache/issues/5)

**Comment by IRMobydick** [comment]
Is there any progress for this feature?

**Comment by danikula** [comment]
This issue duplicates [this](https://github.com/danikula/AndroidVideoCache/issues/5). Let's discuss it in [this](https://github.com/danikula/AndroidVideoCache/issues/5) thread.
