### ISSUE TITLE
Cache size falls over limit if the downloaded file is larger than limit

### ISSUE THREAD

**Issue by metalurgus** [danikula/AndroidVideoCache#72]
I know that it is kind of natural behavior, but I think that something can be done about it.

So problem is that if I set the limit of cache size to 100 MB, then the application cache size can increase over the limit if the downloaded file is larger than 100 MB itself.

**Comment by danikula** [comment]
@metalurgus How do you suggest resolve it? I think you as developer of app that uses AndroidVideoCache should know approximate size of videos your app show. So you must set cache size based on size of videos.

**Comment by metalurgus** [comment]
The cache size is the user's preference. Not my. I suggest to check if the video size fits cache size, and if not - not to cache it at all.

**Comment by danikula** [comment]
If one vides fits all cache size then something wrong with your cache size.
