### ISSUE TITLE
Add method to check if the url (file) is already cached

### ISSUE THREAD

**Issue by metalurgus** [danikula/AndroidVideoCache#73]
I think that it will be very useful to be able to check if the file has already been cached, and is stored in the cache currently. This way we'll be able to show if there is no need to waste traffic, and the file can be played _offline_

**Comment by mackzheng** [comment]
@metalurgus    I agree with your.  I have encountered the same problem。  the same URL  send request twice , the cache file be rewrited.

**Comment by jiaruiz** [comment]
+1

**Comment by wincoke** [comment]
agree！！！

**Comment by danikula** [comment]
@metalurgus I've implemented it in 2.4.0. See details [here](https://github.com/danikula/AndroidVideoCache#listen-caching-progress)

**Comment by danikula** [comment]
@mackzheng Are you sure file is rewrote?
