### ISSUE TITLE
Cached file is not used

### ISSUE THREAD

**Issue by moxiaohu** [danikula/AndroidVideoCache#74]
Do not play already cached video when there is internet and cached video works only in offline mode.

When there is internet, it always download again and again and do not use cached video

**Comment by danikula** [comment]
@moxiaohu It can happen if you try to cache video bigger than 50mb with default caching settings. [this commit](https://github.com/danikula/AndroidVideoCache/commit/582832f8b5c68e55cfb083c3d01f024d42c77d9d) from version 2.5.0 should help you.
