### ISSUE TITLE
200 OK response without content

### ISSUE THREAD

**Issue by nandehutu0123** [danikula/AndroidVideoCache#78]
When I use an invalid url（with no data ,but response 200 OK，The SDK will send request all the way, and the mediaplayer will report no error ,so mediaplayer will loading continuously.

**Comment by danikula** [comment]
@nandehutu0123  If servers returns 200 OK then AndroidVideoCache will return 200 OK. MediaPlayer should work the same way as with original url as proxied url.

**Comment by nandehutu0123** [comment]
@danikula  Thanks for your replay , Thle MediaPlayer work the different as with original url(invalid url) as proxied url.MediaPlayer  will report the error when i use orignal , but when i use sdk ，the MediaPlayer  will  prepare all the way。when I debug the sdk, I found  because of the newheaders(the sdk write)，so it judges no completed and request the original url continuously(because the urlconnection length (-1) unequal to the cache length)。

**Comment by danikula** [comment]
@nandehutu0123 for empty 200 OK responses `AndroidVideoCache` works well. It creates empty cache file and use it as completed cache. It doesn't add additional requests because it has completed cache. MediaPlayer reacts in same way as for original url:
```
I/Pinger: Ping response: `ping ok`, pinged? true
D/VideoFragment: Use proxy url http://127.0.0.1:48905/https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F15506779%2Fempty.txt instead of original url https://dl.dropboxusercontent.com/u/15506779/empty.txt
W/MediaPlayer: Couldn't open file on client side; trying server side: java.io.FileNotFoundException: No content provider: http://127.0.0.1:48905/https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F15506779%2Fempty.txt
D/VideoFragment: onCacheAvailable. percents: 100, file: /storage/emulated/0/Android/data/com.danikula.videocache.sample/cache/video-cache/11072150f17dad2ef359417c6211861c.txt, url: https://dl.dropboxusercontent.com/u/15506779/empty.txt
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
D/VideoView: Error: 1,-2147483648
```

If you can reproduce problem you described with the latest version of library please let me know.
