### ISSUE TITLE
Any idea about audio cached in android ?

### ISSUE THREAD

**Issue by pawarlalit29** [danikula/AndroidVideoCache#8]
Any idea about audio cached in android ?

**Comment by danikula** [comment]
Same code as for video caching. Just use use url from proxy and pass it to [MediaPlayer.setDataSource(Context, Uri) method](http://developer.android.com/reference/android/media/MediaPlayer.html#setDataSource(android.content.Context, android.net.Uri)). Please ket me know if you have any problem with this approach.

**Comment by pawarlalit29** [comment]
thanks, i will try soon

**Comment by pawarlalit29** [comment]
thanks man ,its work smoothly :+1:

**Comment by danikula** [comment]
:+1:
