### ISSUE TITLE
did AndroidVideoCache support seek operation?

### ISSUE THREAD

**Issue by dinglj7** [danikula/AndroidVideoCache#80]
did AndroidVideoCache support seek operation? I use this cool library, but it always download orderly, when I seek  a new position it dont cached, it always download orderly

**Comment by dinglj7** [comment]
as I found that , when I seek the position beyond  the cachelength+ extralength
cacheAvailable + sourceLength * NO_CACHE_BARRIER;

the cachelistener do not work anymore， unless  seek the position less than it.

**Comment by danikula** [comment]
@dinglj7 Yes, the latest version 2.5.0 allows to seek to any position. But it caches always **consequentially** even if you seek to not downloaded area it will continue to cache consequentially.

**Comment by danikula** [comment]
> as I found that , when I seek the position beyond the cachelength+ extralength
> cacheAvailable + sourceLength * NO_CACHE_BARRIER;
> 
> the cachelistener do not work anymore， unless seek the position less than it.

Do you use 2.5.0 version? It should be fixed in 2.5.0.

**Comment by dinglj7** [comment]
yes.   as I found , when seek position exceed the cacheAvailable bound, responseWithoutCache work over the net, it nomore by the cachefile , so cachelistener do not work during this process. use a new cachefile could help this ?

**Comment by danikula** [comment]
This [issue](https://github.com/danikula/AndroidVideoCache/issues/43) can interrupt caching process if you seek to uncached area with `position > cached position + sourceLength * NO_CACHE_BARRIER`. If caching process is interrupted listener will not notify you about caching progress. Please check version of library `2.5.0`. It has fix for it. If you will have any problem with new version, please, let me know.
