### ISSUE TITLE
It doesn't support hls video streaming..

### ISSUE THREAD

**Issue by shikha7763** [danikula/AndroidVideoCache#83]
I want to use it for **m3u8** link but it is not caching & playing video..Throwing **MalformedURLException** error. But it is working fine with any **mp4** urls.

**Comment by danikula** [comment]
@shikha7763 README says:

> Note `AndroidVideoCache` works only with **direct urls** to media file, it [doesn't support](https://github.com/danikula/AndroidVideoCache/issues/19) any streaming technology like DASH, SmoothStreaming, HLS.
