### ISSUE TITLE
I think avoid init proxy in application

### ISSUE THREAD

**Issue by Dwan-xie** [danikula/AndroidVideoCache#86]
In real app, The application maybe run many times if your app have other service that the proxy maybe init many times at the same time.
Firstly, I think should use a thread-save singleton init method. 
Secondly, Init the proxy in app's main process.

**Comment by danikula** [comment]
@Dwan-xie It is up to how you init the library. It is out of AndroidVideoCache's scope. Just make sure you use single instance of HttpProxyCache. If it possible in your app to run initialization code in different threads at the same time just synchronize it. It is up to you.
