### ISSUE TITLE
Partial cacheing of mp4 stream

### ISSUE THREAD

**Issue by xylik** [danikula/AndroidVideoCache#89]
Hi, does your library support cacheing just small part of mp4 stream - lets say 2seconds in the middle of lets say 30 seconds video ?

**Comment by danikula** [comment]
@xylik No. Library always caches files from file's 1st byte. 
It allows partial caching. In this case library caches file from 1ft byte until client (MediaPlayer or another client) cancel streaming. 
Library can't cache part of video from middle.

**Comment by xylik** [comment]
Thanks for reply, am currently trying to create partial cache in the middle of the mp4 stream. Am curious why no one created it yet, is there some nasty problem am not aware of? Am trying to achieve cache to which i just give start milliseconds, end milliseconds and url of mp4 file. I found a way to do it with ffmpeg but currently i have problem building ffmpeg with openssl support so i could cache https streams. Also i referenced ffmpeg approach on the link below.

http://stackoverflow.com/questions/39621736/seek-and-cut-mp4-http-stream-on-the-fly-with-mp4parser-java-library

**Comment by danikula** [comment]
@xylik As I understand you want to cache only those parts of video which user see. Let's imagine user seek to 00:10, then watch video 00:10-00:30, then seek to 00:40 and watch 00:40-00:55. It this case your cache will contain 2 parts of video. Am I right?

**Comment by xylik** [comment]
@danikula Hey, am just interesting in 1 part cache, user wont be able to seek on video he will just play video segment which will be continuos video segment somwhere in the middle of mp4 stream.    This implementation should have just 3 input params: startMS, endMS and video url so i could do cacheing in background thread even before play was requested on that mp4 url. If pre-play video segment cache is not an option am also curious in cacheing while playing. Thanks for your time.

**Comment by danikula** [comment]
@xylik I got your requirements. I think AndroidVideoCache is not good choice in this case. As solution (not really simple) I can offer you to encode new video on the fly using `MediaExtractor`, `MediaCodec`, `MediaMuxer` classes from 16 API. See app `grafika` for examples.
