### ISSUE TITLE
Why HLS is not supported in this  library

### ISSUE THREAD

**Issue by ashish967** [danikula/AndroidVideoCache#91]
I have a video streaming app, which is  completely based on video layout.  Videos are served using hls . I need to cache those video once they gets streamed.

**Comment by danikula** [comment]
@ashish967 read [README](https://github.com/danikula/AndroidVideoCache#features). `AndroidVideoCache` doesn't support any streaming protocol, it supports only direct url based videos. The best choice for you is `ExoPlayer`.
