### ISSUE TITLE
App crashes on view detached while loading video cache 

### ISSUE THREAD

**Issue by cracktechng** [danikula/AndroidVideoCache#95]
App crashes on view detached while loading video cache .

on cases of view detached or pause and the proxy server is still loading resources to cache, it crashes the application.

**Comment by danikula** [comment]
Please, provide stacktrace. Please change `sample` app to reproduce problem.

**Comment by cracktechng** [comment]
com.kolobi.android.model.Post@2db8cc03] 10-15 17:22:23.609 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:23.729 5986-6241/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:23.733 5986-6241/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:24.830 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:24.838 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:25.024 5986-6022/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:25.030 5986-6022/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:30.032 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:30.732 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:31.533 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:31.967 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:32.415 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:32.419 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:32.641 5986-6241/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:32.650 5986-6241/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:33.336 5986-5986/com.kolobi.android I/kolobi: onDetachedFromWindow 10-15 17:22:35.836 5986-5996/com.kolobi.android W/art: Suspending all threads took: 18.549ms 10-15 17:22:35.917 5986-6589/com.kolobi.android I/Pinger: Ping response: `ping ok`, pinged? true 10-15 17:22:35.918 5986-5986/com.kolobi.android I/HttpProxyCacheServer: Proxy cache server started. Is it alive? true 10-15 17:22:35.930 5986-6589/com.kolobi.android I/Pinger: Ping response: `ping ok`, pinged? true 10-15 17:22:35.931 5986-5986/com.kolobi.android I/VideoView: Open Video 10-15 17:22:35.945 5986-5986/com.kolobi.android E/MediaPlayer-JNI: QCMediaPlayer mediaplayer NOT present 10-15 17:22:35.976 5986-5986/com.kolobi.android I/VideoView: SetDataSource 10-15 17:22:35.977 5986-5986/com.kolobi.android D/MediaPlayer: Couldn't open file on client side, trying server side 10-15 17:22:35.999 5986-6003/com.kolobi.android D/MediaHTTPConnection: filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.0.2) 10-15 17:22:36.001 5986-6004/com.kolobi.android D/MediaHTTPConnection: proxy null port 0 10-15 17:22:36.338 5986-5996/com.kolobi.android W/art: Suspending all threads took: 6.760ms 10-15 17:22:36.630 5986-6597/com.kolobi.android D/MediaHTTPConnection: proxy null port 0 10-15 17:22:41.325 5986-5986/com.kolobi.android I/kolobi: Listennng:49 % 10-15 17:22:42.599 5986-6596/com.kolobi.android E/HttpProxyCacheServer: HttpProxyCacheServer error com.danikula.videocache.ProxyCacheException: Error closing socket output stream at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:294) at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270) at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242) at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52) at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) at java.util.concurrent.FutureTask.run(FutureTask.java:237) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) at java.lang.Thread.run(Thread.java:818) Caused by: java.net.SocketException: shutdown failed: ENOTCONN (Transport endpoint is not connected) at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:377) at java.net.Socket.shutdownOutput(Socket.java:652) at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291) at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)� at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)� at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)� at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)� at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)� at java.util.concurrent.FutureTask.run(FutureTask.java:237)� at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)� at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)� at java.lang.Thread.run(Thread.java:818)� Caused by: android.system.ErrnoException: shutdown failed: ENOTCONN (Transport endpoint is not connected) at libcore.io.Posix.shutdown(Native Method) at libcore.io.ForwardingOs.shutdown(ForwardingOs.java:149) at java.net.PlainSocketImpl.shutdownOutput(PlainSocketImpl.java:375) at java.net.Socket.shutdownOutput(Socket.java:652)� at com.danikula.videocache.HttpProxyCacheServer.closeSocketOutput(HttpProxyCacheServer.java:291)� at com.danikula.videocache.HttpProxyCacheServer.releaseSocket(HttpProxyCacheServer.java:270)� at com.danikula.videocache.HttpProxyCacheServer.processSocket(HttpProxyCacheServer.java:242)� at com.danikula.videocache.HttpProxyCacheServer.access$200(HttpProxyCacheServer.java:52)� at com.danikula.videocache.HttpProxyCacheServer$SocketProcessorRunnable.run(HttpProxyCacheServer.java:337)� at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)� at java.util.concurrent.FutureTask.run(FutureTask.java:237)� at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)� at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)� at java.lang.Thread.run(Thread.java:818)� 10-15 17:22:50.799 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:50.803 5986-6240/com.kolobi.android D/skia: --- SkImageDecoder::Factory returned null 10-15 17:22:51.244 5986-5995/com.kolobi.android I/art: Thread[5,tid=5995,WaitingInMainSignalCatcherLoop,Thread*=0xb7ff5350,peer=0x12c00080,"Signal Catcher"]: reacting to signal 3 10-15 17:22:51.711 5986-5995/com.kolobi.android E/art: Unable to open stack trace file '/data/anr/traces.txt': Permission denied

**Comment by danikula** [comment]
@cracktechng can you reproduce it on `sample` app?

**Comment by cracktechng** [comment]
Issue not related to video cache. Gonna close the issue
