### ISSUE TITLE
Deleting from cache

### ISSUE THREAD

**Issue by Anonomousxxx** [danikula/AndroidVideoCache#97]
Is it possible to delete a video from cache manually?

**Comment by danikula** [comment]
@Anonomousxxx yes. Use `FileNameGenerator` to get cache's file name from url and delete it.

**Comment by neslihanturan** [comment]
But the problem is, library does not recognize the file is deleted, thus tries to read a non-existent file. Gives me "ProxyCacheException: Error reading length of file" naturally. How can I warn the library about non-existence of file?

**Comment by RowlandOti** [comment]
If this question had been answered. m Y issue ewoul ldo get solvs
